name: hdp_dev
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - xarray
  - cartopy
  - numpy
  - numba
  - nc-time-axis
  - dask
  - zarr
  - netCDF4
  - tqdm
  - ipywidgets
  - nbformat
  - pytest