name: Draft JOSS PDF
on:
  push:
    paths:
      - docs/joss/**
      - .github/workflows/draft-pdf.yml
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: docs/joss/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: docs/joss/paper.pdf